version: '3'
services:
  vscode-remote-node:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: node
    tty: true
  vscode-remote-httpbin:
    image: kennethreitz/httpbin:latest
    hostname: httpbin
