version: '3'
services:
  #  node:
  #    image: 'ghcr.io/hankei6km/h6-dev-containers:node'
  #    hostname: node
  #    tty: true
  node:
    image: 'kennethreitz/httpbin:latest'
    hostname: httpbin
